### PR TITLE
Making it compatible with dotnet 3.1 (2.2 is no longer supported)

### PR DESCRIPTION
**Pull request by moreirayokoyama**
[Microsoft is no longer supporting Dotnet Core 2.2](https://dotnet.microsoft.com/download/dotnet-core)

The recommended version of dotnet core is 3.1 (Long-term support). Anyone with 3.1 installed couldn't run the tests due to incompatibility issues.

Also, when running the tests using Windows Subsystem for Linux (WSL 2), one of the tests was failing due to a label which was present for all docker containers started on WSL 2 (which indicates which Linux distro is being used). So there's a commit making it pass by supporting multiple labels while still asserting the presence of the custom label itself.

Finally, there's a commit from the result of running `dotnet format` as instructed in the Contributing Guidelines.

### CODE REVIEW

**Review by isen-ng — APPROVED** [review]
LGTM

**Comment by swissarmykirpan** [comment]
@moreirayokoyama seems to be an issue in CI, might have something to do with the version of cake

**Comment by moreirayokoyama** [comment]
> @moreirayokoyama seems to be an issue in CI, might have something to do with the version of cake

Yeah. I admit I was not aware of that before submitting the PR. After seeing the AppVeyor build failing and the reason for that I tried to run it as it shows in the log (`./build.sh --target=Restore-NuGet-Packages`) and the output I got was even worse. I'm not sure mono is compatible with WSL 2, but suck with shell scripting and can't fix it.

**Comment by moreirayokoyama** [comment]
I was able to run the powershell version by changing the `global.json` file to use sdk 3.1 (I was using a more specific version 3.1.302 before). But it keeps failing.

**Comment by moreirayokoyama** [comment]
Ok. I'm still unable to run this script in WSL 2, and in Powershell I didn't have any issues. So I could not reproduce the problem. But at least by updating Cake it is now successfully building in CI.

**Review by swissarmykirpan — APPROVED** [review]

**Pull request merged**
