### PR TITLE
feature/editor config

### PR DESCRIPTION
**Pull request by isen-ng**
Copied mainly from https://github.com/dotnet/coreclr/blob/master/.editorconfig

rozlyn vs editorconfig?

> "Ruleset" and ".editorconfig" files are themselves not doing any analysis, but are just configuration files that determine/configure behavior of installed analyzers. Rulesets are the legacy file format used for analysis configuration, and we are slowly moving towards replacing them with .editorconfig based configuration.

https://github.com/dotnet/roslyn-analyzers/issues/1844#issuecomment-427422189

### CODE REVIEW

**Comment by isen-ng** [comment]
Closes https://github.com/testcontainers/testcontainers-dotnet/issues/42

**Comment by isen-ng** [comment]
Should we ask PRs to run `dotnet format` before merging?

https://www.hanselman.com/blog/EditorConfigCodeFormattingFromTheCommandLineWithNETCoresDotnetFormatGlobalTool.aspx

**Review by HofmeisterAn — COMMENTED** [review]
I prefer `indent_size` of 2 for `.cs` files as well, apart from that LGTM.

**Comment by isen-ng** [comment]
I personally prefer `indent_size` side of 4. What do you think @swissarmykirpan?

**Comment by swissarmykirpan** [comment]
I also prefer 4 :)

**Comment by isen-ng** [comment]
Democracy! haha jk!
I'll need a review approval to merge this.

Edit: I've also added `CONTRIBUTING.md` with it's first section on `.editorconfig`

**Review by swissarmykirpan — APPROVED** [review]

**Pull request merged**
