### PR TITLE
#50 Add SonarCloud statistics to build pipeline

### PR DESCRIPTION
**Pull request by HofmeisterAn**
Switch over from coveralls.net to SonarCloud

### CODE REVIEW

**Comment by HofmeisterAn** [comment]
@swissarmykirpan as soon as the environment variables exists in AppVeyor, the build should create the SonarCloud statistics.
- [x] SONARQUBE_URL = `https://sonarcloud.io`
- [x] SONARQUBE_KEY = `testcontainers_testcontainers-dotnet`
- [x] SONARQUBE_TOKEN = See Slack channel, use secure variable.
- [ ] SONARQUBE_ORGANIZATION = `testcontainers`

**Comment by isen-ng** [comment]
@HofmeisterAn this will also upload the code coverage to sonarcloud?

**Comment by HofmeisterAn** [comment]
> @HofmeisterAn this will also upload the code coverage to sonarcloud?

Yes. This will upload static code analysis, test and coverage results for every built branch. SonarCloud will remove old branches automatically.

**Comment by isen-ng** [comment]
Sweet! LGTM!

**Review by isen-ng — APPROVED** [review]

**Review by swissarmykirpan — APPROVED** [review]

**Pull request merged**
