### PR TITLE
Using this to discuss .editorconfig

### PR DESCRIPTION
**Pull request by isen-ng**
1. Updated .editorconfig to preserve some of the new line features
2. Run `dotnet format` on the solution

We can discuss the results of `dotnet format` in this PR.
Because the other PR has no code changes, when that is merged, I can easily rebase and run `dotnet format` again.

### CODE REVIEW

**Review by HofmeisterAn — CHANGES_REQUESTED** [review]
Shouldn't we add a default value for `end_of_line` as well? Apart from that, I agree with everything as long as it is consistent.

**Comment by isen-ng** [comment]
> Shouldn't we add a default value for end_of_line as well?

Since we are doing dotnet, we should set the `end_of_line` as `crlf` (to support both windows and linux).

What do you all think?

**Comment by isen-ng** [comment]
What about `max_line_length`?
For readability, we should also set this.

`80` or `120`? 
I personally prefer 120.

**Comment by HofmeisterAn** [comment]
> Since we are doing dotnet, we should set the `end_of_line` as `crlf` (to support both windows and linux).
> 
> What do you all think?

I don't think it makes much difference these days. However, I prefer lf on the Unix bash. But I can accept crlf as well.

> `80` or `120`?

Definitely `120` we all have widescreens.

**Comment by isen-ng** [comment]
Added 

* `end_of_line = lf`
* `max_line_length = 120`

**Review by swissarmykirpan — APPROVED** [review]

**Review by HofmeisterAn — APPROVED** [review]

**Pull request merged**
