### PR TITLE
Merge master to a branch from develop

### PR DESCRIPTION
**Pull request by isen-ng**
* Resolved all merge conflicts
* Updated dotnet sdk from "2.2.300" to "2.2.401"
  * "2.2.301" is not working for appveyor, they require "2.2.400"
  * I don't know why, "2.2.400" does not work for my local builds, only "2.2.401" works

### CODE REVIEW

**Comment by HofmeisterAn** [comment]
AppVeyor updated the .NET Core SDK version on August to 2.2.401. Should we update the version in `global.json` first? Unfortunately, the update without backwards compatibility...

**Comment by isen-ng** [comment]
For the oddest reason, setting the sdk version to "2.2.400" does not work for me. The projects refuse to build.

It only works with "2.2.401" even though the [documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) for it says that "2.2.400" should work when I only have 2.2.401 installed.

**Comment by isen-ng** [comment]
> AppVeyor updated the .NET Core SDK version on August to 2.2.401.

Hmm this is not fun. Instead of updating their image to 2.2.401, they should install 2.2.301, and 2.2.401 (and other supported versions) in parallel. This means, every time they update, we are forced to update. 

This won't be fun. There should be a smarter way to do this.

**Comment by HofmeisterAn** [comment]
> This won't be fun. There should be a smarter way to do this.

Yea, I don't like this either. [This](https://www.appveyor.com/updates/) doc says the updated to 2.2.401, which should work with 2.2.400.

**Comment by isen-ng** [comment]
> which should work with 2.2.400

This doesn't build for me on my local machine. It throws this exception and refuses to build the test projects

```
Microsoft.NET.TargetFrameworkInference.targets(137, 5): The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.
```

It only works when I set the version to "2.2.401"...

Edit:
And I do have dotnet 2.2.401 installed

```
$ dotnet --list-sdks
2.2.205 [/usr/local/share/dotnet/sdk]
2.2.301 [/usr/local/share/dotnet/sdk]
2.2.401 [/usr/local/share/dotnet/sdk]
```

**Comment by HofmeisterAn** [comment]
I won't bother you again, but could you add  [this](https://github.com/testcontainers/testcontainers-dotnet/pull/65/files#diff-b25fdcb38f35bd4e3e9ddf4a608defc9) fix for `build/version.cake` too? This would fix our SonarCould statistics again.

I will check later that day if I have any issues with `2.2.400` on my local machine.

**Review by HofmeisterAn — APPROVED** [review]

**Comment by isen-ng** [comment]
Looks like appveyor likes "2.2.400"

**Comment by HofmeisterAn** [comment]
Great! If this is merged, I'll update #65 and we can hopefully start with a new milestone. @isen-ng your suggestion from 19.06 would be nice!

**Review by swissarmykirpan — APPROVED** [review]

**Pull request closed without merging**
